apiVersion: v1
kind: Service
metadata:
  name: olivetti-faces-service
spec:
  type: NodePort
  selector:
    app: olivetti-faces-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
